
# Gem::Specification for Fastthread-1.0.1
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{fastthread}
  s.version = "1.0.1"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["MenTaLguY <mental@rydia.net>"]
  s.date = %q{2007-10-26}
  s.description = %q{Optimized replacement for thread.rb primitives}
  s.email = %q{}
  s.extensions = ["ext/fastthread/extconf.rb"]
  s.files = ["test/test_queue.rb", "test/test_mutex.rb", "test/test_condvar.rb", "test/test_all.rb", "setup.rb", "Manifest", "ext/fastthread/fastthread.c", "ext/fastthread/extconf.rb", "CHANGELOG", "fastthread.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{}
  s.require_paths = ["lib", "ext"]
  s.rubyforge_project = %q{mongrel}
  s.rubygems_version = %q{0.9.4.6}
  s.summary = %q{Optimized replacement for thread.rb primitives}
  s.test_files = ["test/test_all.rb"]
end


# # Original Rakefile source (requires the Echoe gem):
# 
# 
# require 'echoe'
# 
# Echoe.new("fastthread") do |p|
#   p.project = "mongrel"
#   p.author = "MenTaLguY <mental@rydia.net>"
#   p.summary = "Optimized replacement for thread.rb primitives"
#   p.extensions = "ext/fastthread/extconf.rb"
#   p.clean_pattern = ['build/*', '**/*.o', '**/*.so', '**/*.a', 'lib/*-*', '**/*.log', "ext/fastthread/*.{bundle,so,obj,pdb,lib,def,exp}", "ext/fastthread/Makefile", "pkg", "lib/*.bundle", "*.gem", ".config"]
# 
#   p.need_tar_gz = false
#   p.need_tgz = true
#   p.require_signed = true
# 
#   p.eval = proc do  
#     if RUBY_PLATFORM.match("win32")
#       platform = Gem::Platform::WIN32
#       files += ['lib/fastthread.so']
#       task :package => [:clean, :compile]
#     end
#   end
# 
# end
