# Set bundle path to ./gems
bundle_path "gems"

# dependencies are generated using a strict version, don't forget to edit the dependency versions when upgrading.
merb_gems_version = "<%= merb_gems_version %>"

# If you did disable json for Merb, comment out this line.
# If you want use json gem just change it.
# Don't use json gem version lower than 1.1.7! Older versions has security bug!
gem "json_pure", ">= 1.1.7"
gem "merb-core", merb_gems_version

<%= gems_for_orm(orm) %>
<%= gems_for_template_engine(template_engine) %>
<%= gems_for_testing_framework(testing_framework) %>
